version: '3.3'

services:
    test0:
        build: 
            context: .
            args:
                NODE_NUM: 0
                PORT: 8080
                KNOWN_NEIGHBOURS: 2
                BANDWIDTH: 10
                BUFFER_SIZE: 100
                DELAY: 500
                LOSS: 5
                BASE_REDIRECT_URL: http://localhost
        cap_add:
            - NET_ADMIN
            - SYS_ADMIN
        ports:
            - 8080:8080
            - 58080:58080

    test1:
        build: 
            context: .
            args:
                NODE_NUM: 1
                PORT: 8081
                KNOWN_NEIGHBOURS: 2
                BANDWIDTH: 10
                BUFFER_SIZE: 100
                DELAY: 1000
                LOSS: 5
                BASE_REDIRECT_URL: http://localhost
        cap_add:
            - NET_ADMIN
            - SYS_ADMIN
        ports:
            - 8081:8081
            - 58081:58081

    test2:
        build: 
            context: .
            args:
                NODE_NUM: 2
                PORT: 8082
                KNOWN_NEIGHBOURS: 2
                BANDWIDTH: 10
                BUFFER_SIZE: 100
                DELAY: 1000
                LOSS: 5
                BASE_REDIRECT_URL: http://localhost
        cap_add:
            - NET_ADMIN
            - SYS_ADMIN
        ports:
            - 8082:8082
            - 58082:58082

    test3:
        build: 
            context: .
            args:
                NODE_NUM: 3
                PORT: 8083
                KNOWN_NEIGHBOURS: 2
                BANDWIDTH: 10
                BUFFER_SIZE: 100
                DELAY: 1000
                LOSS: 5
                BASE_REDIRECT_URL: http://localhost
        cap_add:
            - NET_ADMIN
            - SYS_ADMIN
        ports:
            - 8083:8083
            - 58083:58083

    test4:
        build: 
            context: .
            args:
                NODE_NUM: 4
                PORT: 8084
                KNOWN_NEIGHBOURS: 2
                BANDWIDTH: 10
                BUFFER_SIZE: 100
                DELAY: 10000
                LOSS: 5
                BASE_REDIRECT_URL: http://localhost
        cap_add:
            - NET_ADMIN
            - SYS_ADMIN
        ports:
            - 8084:8084
            - 58084:58084
